spring.application.name=quickks-provider-service


server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/quickks_db
spring.datasource.username=root
spring.datasource.password=Pass@2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true